src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ServiceRepository::class)]
class Service
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_annonce = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $categorie = null;

    #[ORM\ManyToOne(inversedBy: 'services')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateAnnonce(): ?\DateTimeInterface
    {
        return $this->date_annonce;
    }

    public function setDateAnnonce(\DateTimeInterface $date_annonce): self
    {
        $this->date_annonce = $date_annonce;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/ServiceType.php
<?php

namespace App\Form;

use App\Entity\Service;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ServiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('description')
            ->add('date_annonce', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Publish Date',
            ])
            ->add('adresse')
            ->add('categorie')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Service::class,
        ]);
    }
}

src/Controller/ServiceController.php
<?php

namespace App\Controller;

use App\Entity\Service;
use App\Form\ServiceType;
use App\Repository\ServiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('admin/service')]
class ServiceController extends AbstractController
{
    #[Route('/', name: 'app_service_index', methods: ['GET'])]
    public function index(ServiceRepository $serviceRepository): Response
    {
        return $this->render('service/index.html.twig', [
            'services' => $serviceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_service_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ServiceRepository $serviceRepository): Response
    {
        $service = new Service();
        $form = $this->createForm(ServiceType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $serviceRepository->save($service, true);

            return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('service/new.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_service_show', methods: ['GET'])]
    public function show(Service $service): Response
    {
        return $this->render('service/show.html.twig', [
            'service' => $service,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_service_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Service $service, ServiceRepository $serviceRepository): Response
    {
        $form = $this->createForm(ServiceType::class, $service);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $serviceRepository->save($service, true);

            return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('service/edit.html.twig', [
            'service' => $service,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_service_delete', methods: ['POST'])]
    public function delete(Request $request, Service $service, ServiceRepository $serviceRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$service->getId(), $request->request->get('_token'))) {
            $serviceRepository->remove($service, true);
        }

        return $this->redirectToRoute('app_service_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/service/_delete_form.html.twig
<form method="post" action="{{ path('app_service_delete', {'id': service.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ service.id) }}">
    <button class="btn">Delete</button>
</form>

templates/service/_form.html.twig
{{ form_start(form) }}

<div class="row">
    <div class="col-lg-6">
        <div class="mb-3">
            {{ form_label(form.titre, 'Service Title', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.titre, {'attr': {'class': 'form-control'}}) }}
        </div>

        <div class="mb-3">
            {{ form_label(form.description, 'Description', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.description, {'attr': {'class': 'form-control', 'rows': 2}}) }}
        </div>
        <div class="mb-3">
                <label for="{{ form.date_annonce.vars.id }}" class="form-label">{{ form.date_annonce.vars.label }}</label>
                {{ form_widget(form.date_annonce, {
                    'attr': {'class': 'form-control', 'placeholder': 'Announce date', 'id': 'basic-datepicker'}
                }) }}
        </div>
    </div>
    <div class="col-lg-6">
        <div class="mb-3">
            {{ form_label(form.adresse, 'Location', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.adresse, {'attr': {'class': 'form-control', 'placeholder': 'location'}}) }}
        </div>

        <div class="mb-3">
            {{ form_label(form.categorie, 'Service Category', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.categorie, {'attr': {'class': 'form-control', 'placeholder': 'Category'}}) }}
        </div>

        <div class="mb-3">
            {{ form_label(form.user, 'Service Owner', {'label_attr': {'class': 'form-label'}}) }}
            {{ form_widget(form.user, {'attr': {'class': 'form-select'}}) }}
        </div>
    </div>
</div>

<button class="btn">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

templates/service/edit.html.twig
{% extends 'baseadmin.html.twig' %}

{% block title %}Edit Service{% endblock %}

{% block body %}
    <h1>Edit Service</h1>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    {{ include('service/_form.html.twig', {'button_label': 'Update'}) }}
                    <!-- end row-->

                </div> <!-- end card-body -->
            </div> <!-- end card -->
        </div><!-- end col -->
    </div>


    <a href="{{ path('app_service_index') }}">back to list</a>

    {{ include('service/_delete_form.html.twig') }}
{% endblock %}

{% block javascripts %}
    {{ parent()}}
    <!-- Plugins js-->
    <script src="{{ asset('../admin/assets/libs/flatpickr/flatpickr.min.js') }}"></script>
    <script src="{{ asset('../admin/assets/libs/spectrum-colorpicker2/spectrum.min.js') }}"></script>
    <script src="{{ asset('../admin/assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>

    <!-- Init js-->
    <script src="{{ asset('../admin/assets/js/pages/form-pickers.init.js') }}"></script>

{% endblock %}

templates/service/index.html.twig
{% extends 'baseadmin.html.twig' %}


{% block body %}
    <div class="col-xl-8" style="width: auto !important;">
        <div class="card">
            <div class="card-body">


                <h1 class="header-title mt-0 mb-3">Liste Services</h1>

                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead>
                        <tr>
                            <th>Titre Service</th>
                            <th>Description</th>
                            <th>Publish Date</th>
                            <th>Location</th>
                            <th>Categorie</th>
                            <th>Owner</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for service in services %}
                            <tr>
                                <td>{{ service.titre }}</td>
                                <td style="max-width: 20vw">{{ service.description }}</td>
                                <td>{{ service.dateAnnonce ? service.dateAnnonce|date('Y-m-d') : '' }}</td>
                                <td>{{ service.adresse }}</td>
                                <td><span class="badge bg-danger">{{ service.categorie }}</span></td>
                                <td>{{ service.user.nom }}</td>

                                <td>
                                    <a href="{{ path('app_service_show', {'id': service.id}) }}">show</a>
                                    <a href="{{ path('app_service_edit', {'id': service.id}) }}">edit</a>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="7">no records found</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div><!-- end col -->
    <a href="{{ path('app_service_new') }}">Create new</a>
{% endblock %}

templates/service/new.html.twig
{% extends 'baseadmin.html.twig' %}

{% block title %}New Service{% endblock %}

{% block body %}
    <h1>Create new Service</h1>

    {{ include('service/_form.html.twig') }}

    <a href="{{ path('app_service_index') }}">back to list</a>
{% endblock %}

templates/service/show.html.twig
{% extends 'baseadmin.html.twig' %}

{% block title %}Service{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link href="{{asset('../admin/assets/libs/sweetalert2/sweetalert2.min.css')}}" rel="stylesheet" type="text/css" />

    <!-- App css -->
    <link href="{{asset('../admin/assets/css/config/default/bootstrap.min.css')}}" rel="stylesheet" type="text/css" id="bs-default-stylesheet" />
    <link href="{{asset('../admin/assets/css/config/default/app.min.css')}}" rel="stylesheet" type="text/css" id="app-default-stylesheet" />

    <link href="{{asset('../admin/assets/css/config/default/bootstrap-dark.min.css')}}" rel="stylesheet" type="text/css" id="bs-dark-stylesheet" disabled="disabled" />
    <link href="{{asset('../admin/assets/css/config/default/app-dark.min.css')}}" rel="stylesheet" type="text/css" id="app-dark-stylesheet" disabled="disabled" />

    <!-- icons -->
    <link href="{{asset('../admin/assets/css/icons.min.css')}}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block body %}
    <h1>Service</h1>
    <div style="
    flex: auto;
    text-align: -webkit-center;">
    <div class="col-xl-3 col-md-6">
        <div class="card">
            <div class="text-center card-body">

                <div>
                    <img src="{{ asset('../admin/assets/images/users/user-1.jpg') }}" class="rounded-circle avatar-xl img-thumbnail mb-3" alt="profile-image">

                    <p class="text-muted font-13 mb-4">
                        {{ service.description }}
                    </p>

                    <div class="text-start">
                        <p class="text-muted font-13"><strong>Service Title :</strong> <span class="ms-2">{{ service.titre }}</span></p>
                        <p class="text-muted font-13"><strong>Category :</strong><span class="ms-2 badge bg-danger">{{ service.categorie }}</span></p>
                        <p class="text-muted font-13"><strong>Published On :</strong> <span class="ms-2">{{ service.dateAnnonce ? service.dateAnnonce|date('Y-m-d') : '' }}</span></p>
                        <p class="text-muted font-13"><strong>Owner Name :</strong> <span class="ms-2">{{ service.user.nom }}</span></p>
                        <p class="text-muted font-13"><strong>Mobile :</strong><span class="ms-2">+216 {{ service.user.phone }}</span></p>
                        <p class="text-muted font-13 m-b-5"><strong>Location :</strong> <span class="ms-2">{{ service.adresse }}</span></p>

                    </div>

                </div>

            </div>
        </div>
    </div>
    </div>



    <a href="{{ path('app_service_index') }}">back to list</a>

    <a href="{{ path('app_service_edit', {'id': service.id}) }}">edit</a>

    {{ include('service/_delete_form.html.twig') }}
{% endblock %}