src/Entity/Livraison.php
<?php

namespace App\Entity;

use App\Repository\LivraisonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LivraisonRepository::class)]
class Livraison
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToMany(mappedBy: 'livraison', targetEntity: Commande::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $commandes;

    #[ORM\ManyToOne(inversedBy: 'livraisons')]
    private ?User $livreur = null;

    #[ORM\ManyToOne(inversedBy: 'livraisons')]
    private ?User $client = null;

    #[ORM\Column(length: 255)]
    private ?string $destination = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_livraison = null;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setLivraison($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getLivraison() === $this) {
                $commande->setLivraison(null);
            }
        }

        return $this;
    }

    public function getLivreur(): ?User
    {
        return $this->livreur;
    }

    public function setLivreur(?User $livreur): self
    {
        $this->livreur = $livreur;

        return $this;
    }

    public function getClient(): ?User
    {
        return $this->client;
    }

    public function setClient(?User $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(string $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getDateLivraison(): ?\DateTimeInterface
    {
        return $this->date_livraison;
    }

    public function setDateLivraison(\DateTimeInterface $date_livraison): self
    {
        $this->date_livraison = $date_livraison;

        return $this;
    }
}

src/Controller/DeliveryController.php
<?php
namespace App\Controller;

use App\Entity\Commande;
use App\Entity\Livraison;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DeliveryController extends AbstractController
{
    /**
     * @Route("/delivery", name="delivery_index")
     */
    public function index(): Response
    {
        $commandes = $this->getDoctrine()->getRepository(Commande::class)->findAll();

        return $this->render('delivery/delivery_orders.html.twig', [
            'commandes' => $commandes,
        ]);
    }

    /**
     * @Route("/delivery/accept/{id}", name="delivery_accept")
     */
    public function accept($id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $commande = $entityManager->getRepository(Commande::class)->find($id);

        if (!$commande) {
            throw $this->createNotFoundException('No commande found for id '.$id);
        }

        $livraison = new Livraison();
        $livraison->addCommande($commande);
        $livraison->setLivreur($this->getUser());
        $livraison->setClient($commande->getUser());
        $livraison->setDestination($commande->getUser()->getAdresse());
        $date = new DateTime();
        $date->modify('+2 days');
        $livraison->setDateLivraison($date);

        $entityManager->persist($livraison);
        $entityManager->flush();

        return $this->redirectToRoute('mesLivraisons');
    }


    /**
     * @Route("/delivery/orders/{id}", name="delivery_order_detail")
     */
    public function delivery_show_order(Commande $commande): Response
    {
        return $this->render('delivery/delivery_order_detail.html.twig', [
            'commande' => $commande,
        ]);
    }


    /**
     * @Route("/delivery/myDeliveries/", name="mesLivraisons")
     */
    public function listDeliveriesForDeliveryAgent(): Response
    {
        $deliveryAgent = $this->getUser();
        $deliveries = $this->getDoctrine()
            ->getRepository(Livraison::class)
            ->findByDeliveryAgent($deliveryAgent);

        return $this->render('delivery/mes_livraisons.html.twig', [
            'deliveries' => $deliveries,
        ]);
    }
}

templates/delivery/delivery_order_detail.html.twig
{% extends 'baselivreur.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
    <h1>Commande</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commande.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ commande.date ? commande.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Total</th>
                <td>{{ commande.total }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('delivery_index') }}">back to list</a>

    <a href="{{ path('delivery_accept', {'id': commande.id}) }}">Accept</a>

{% endblock %}

templates/delivery/delivery_orders.html.twig
{% extends 'baselivreur.html.twig' %}
{% block dropdownNotif %}{% endblock %}

{% block title %}Commande index{% endblock %}

{% block body %}
    <h1>Commande index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Total</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.date ? commande.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.total }}</td>
                <td>
                    <a href="{{ path('delivery_order_detail', {'id': commande.id}) }}">show</a>
                    <a href="{{ path('delivery_accept', {'id': commande.id}) }}">Accept</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/delivery/mes_livraisons.html.twig
{% extends 'baselivreur.html.twig' %}
{% block title %} Mes Livraisons {% endblock %}
{% block dropdownNotif %} {% endblock %}
{% block body %}
    <h1>Mes Livraisons</h1>

    <table>
        <thead>
        <tr>

            <th>Client</th>
            <th>Adresse</th>
            <th>Date de livraison</th>
        </tr>
        </thead>
        <tbody>
        {% for delivery in deliveries %}
            <tr>

                <td>{{ delivery.client.nom }}</td>
                <td>{{ delivery.client.adresse }}</td>
                <td>{{ delivery.dateLivraison|date('d/m/Y H:i') }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}